# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - id: step1
      uses: actions/checkout@v2
    - id: step2
      name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - id: step3
      name: Determine next tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        INITIAL_VERSION: 0.0.0
        DRY_RUN: true
    - id: step4
      name: Build with Maven
      run: mvn versions:set -DnewVersion=${{ steps.step3.outputs.new_tag }} ; mvn -B package --file pom.xml
    - id: step5
      name: Publish package
      run: mvn --batch-mode deploy
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - id: step6
      name: Create a Release
      uses: elgohr/Github-Release-Action@master
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        args: ${{ steps.step3.outputs.new_tag }}
    - id: step7
      name: Create tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DRY_RUN: false
